//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompactGUI.My.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CompactGUI.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dsmask {
            get {
                object obj = ResourceManager.GetObject("dsmask", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconbright {
            get {
                object obj = ResourceManager.GetObject("iconbright", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Ookii_Dialogs {
            get {
                object obj = ResourceManager.GetObject("Ookii_Dialogs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzing....
        /// </summary>
        internal static string StrAnalyze {
            get {
                return ResourceManager.GetString("StrAnalyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;This directory contains a subfolder that you do not have permission to access. Please try running the program again as an Administrator.&quot;
        ///&quot;If the problem persists, the subfolder is most likely protected by the System, and by design this program will refuse to let you proceed.&quot;
        ///&quot;Would you like to restart the program as an Administrator?&quot;.
        /// </summary>
        internal static string StrAskForAdmin {
            get {
                return ResourceManager.GetString("StrAskForAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot contain &apos;?&apos;, &apos;&amp;&apos;, &apos;|&apos;, &apos;%&apos;, &apos;™&apos;, &apos;®&apos;, or &apos;©&apos;.
        /// </summary>
        internal static string StrBadChars {
            get {
                return ResourceManager.GetString("StrBadChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot compress files in folder. Please check program settings..
        /// </summary>
        internal static string StrCantComp {
            get {
                return ResourceManager.GetString("StrCantComp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string StrClose {
            get {
                return ResourceManager.GetString("StrClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using existing game/prog database.
        /// </summary>
        internal static string StrDBExist {
            get {
                return ResourceManager.GetString("StrDBExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching game/prog database....
        /// </summary>
        internal static string StrDBFetch {
            get {
                return ResourceManager.GetString("StrDBFetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing game/prog database....
        /// </summary>
        internal static string StrDBNew {
            get {
                return ResourceManager.GetString("StrDBNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decompressing....
        /// </summary>
        internal static string StrDeComp {
            get {
                return ResourceManager.GetString("StrDeComp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        internal static string StrDone {
            get {
                return ResourceManager.GetString("StrDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Connection Error.
        /// </summary>
        internal static string StrErrorInternet {
            get {
                return ResourceManager.GetString("StrErrorInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions Error.
        /// </summary>
        internal static string StrErrorPerm {
            get {
                return ResourceManager.GetString("StrErrorPerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated Compressed.
        /// </summary>
        internal static string StrEstComp {
            get {
                return ResourceManager.GetString("StrEstComp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder|#Folder|All Files(*.*)|*.*.
        /// </summary>
        internal static string StrFileDialogFilter {
            get {
                return ResourceManager.GetString("StrFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File selected.
        /// </summary>
        internal static string StrFileSelected {
            get {
                return ResourceManager.GetString("StrFileSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple files selected.
        /// </summary>
        internal static string StrFilesSelected {
            get {
                return ResourceManager.GetString("StrFilesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Decompressing.
        /// </summary>
        internal static string StrFinishDeComp {
            get {
                return ResourceManager.GetString("StrFinishDeComp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressed files are present..
        /// </summary>
        internal static string StrHasComp {
            get {
                return ResourceManager.GetString("StrHasComp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This folder is not compressed..
        /// </summary>
        internal static string StrHasNoComp {
            get {
                return ResourceManager.GetString("StrHasNoComp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressed.
        /// </summary>
        internal static string StrIsComp {
            get {
                return ResourceManager.GetString("StrIsComp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncompressed.
        /// </summary>
        internal static string StrIsUnComp {
            get {
                return ResourceManager.GetString("StrIsUnComp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After.
        /// </summary>
        internal static string StrLblAfter {
            get {
                return ResourceManager.GetString("StrLblAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algorithim.
        /// </summary>
        internal static string StrLblAlgo {
            get {
                return ResourceManager.GetString("StrLblAlgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before.
        /// </summary>
        internal static string StrLblBefore {
            get {
                return ResourceManager.GetString("StrLblBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        internal static string StrLblGame {
            get {
                return ResourceManager.GetString("StrLblGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Name:.
        /// </summary>
        internal static string StrLblGameName {
            get {
                return ResourceManager.GetString("StrLblGameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poorly Compressed Extensions:.
        /// </summary>
        internal static string StrLblPoorlyComp {
            get {
                return ResourceManager.GetString("StrLblPoorlyComp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Name:.
        /// </summary>
        internal static string StrLblProgName {
            get {
                return ResourceManager.GetString("StrLblProgName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratio.
        /// </summary>
        internal static string StrLblRatio {
            get {
                return ResourceManager.GetString("StrLblRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending results....
        /// </summary>
        internal static string StrLblSendResults {
            get {
                return ResourceManager.GetString("StrLblSendResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results Sent!.
        /// </summary>
        internal static string StrLblSentResults {
            get {
                return ResourceManager.GetString("StrLblSentResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduction in size.
        /// </summary>
        internal static string StrLblSizeReduction {
            get {
                return ResourceManager.GetString("StrLblSizeReduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No folder selected.
        /// </summary>
        internal static string StrNotSelected {
            get {
                return ResourceManager.GetString("StrNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program will not compress a whole drive!.
        /// </summary>
        internal static string StrProhibitDrive {
            get {
                return ResourceManager.GetString("StrProhibitDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program will not compress the Windows directory!.
        /// </summary>
        internal static string StrProhibitWindows {
            get {
                return ResourceManager.GetString("StrProhibitWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string StrQuestion {
            get {
                return ResourceManager.GetString("StrQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save console output?.
        /// </summary>
        internal static string StrSaveConsoleOutput {
            get {
                return ResourceManager.GetString("StrSaveConsoleOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Folder or Files.
        /// </summary>
        internal static string StrSelectFiles {
            get {
                return ResourceManager.GetString("StrSelectFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarting momentarily....
        /// </summary>
        internal static string StrTimedRestart {
            get {
                return ResourceManager.GetString("StrTimedRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutting down momentarily....
        /// </summary>
        internal static string StrTimedShutdown {
            get {
                return ResourceManager.GetString("StrTimedShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleeping momentarily....
        /// </summary>
        internal static string StrTimedSleep {
            get {
                return ResourceManager.GetString("StrTimedSleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressing....
        /// </summary>
        internal static string StrWaitComp {
            get {
                return ResourceManager.GetString("StrWaitComp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit?
        ///Quitting now will finish compressing the current file, then quit safely.
        ///If you do decide to quit now, you can resume compression by repeating the process later.
        ///Click Yes to continue exiting the program..
        /// </summary>
        internal static string StrWarnClose {
            get {
                return ResourceManager.GetString("StrWarnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        internal static string StrWarning {
            get {
                return ResourceManager.GetString("StrWarning", resourceCulture);
            }
        }
    }
}
